using Microsoft.Extensions.Logging;
using ZayFlow.Backend.Contracts;
using ZayFlow.Backend.DTOs;
using ZayFlow.Backend.Models;

namespace ZayFlow.Backend.Services;

/// <summary>
/// Logging infrastructure for planner actions and execution details.
/// Provides structured logging for audit trails and debugging.
/// </summary>
public sealed class PlannerActionLogger
{
    private readonly ILogger<PlannerActionLogger> _logger;
    private readonly IExecutionAuditStore _auditStore;

    public PlannerActionLogger(ILogger<PlannerActionLogger> logger, IExecutionAuditStore auditStore)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _auditStore = auditStore ?? throw new ArgumentNullException(nameof(auditStore));
    }

    /// <summary>
    /// Log plan generation.
    /// </summary>
    public void LogPlanGenerated(string plannerType, string userInput, PlanDTO plan)
    {
        _logger.LogInformation(
            "Plan generated by {PlannerType}. Input: '{UserInput}', PlanId: {PlanId}, " +
            "ActionCount: {ActionCount}, RiskLevel: {RiskLevel}",
            plannerType,
            userInput.Length > 50 ? userInput.Substring(0, 47) + "..." : userInput,
            plan.Id,
            plan.Actions.Count,
            plan.RiskLevel);
    }

    /// <summary>
    /// Log plan execution start.
    /// </summary>
    public void LogExecutionStarted(PlanDTO plan, bool isOnline, int tokenBalance)
    {
        _logger.LogInformation(
            "Executing plan {PlanId}. IsOnline: {IsOnline}, TokenBalance: {TokenBalance}, " +
            "ActionCount: {ActionCount}",
            plan.Id, isOnline, tokenBalance, plan.Actions.Count);
    }

    /// <summary>
    /// Log plan execution completion.
    /// </summary>
    public void LogExecutionCompleted(PlanDTO plan, ExecutionResultDTO result)
    {
        _logger.LogInformation(
            "Plan execution completed. PlanId: {PlanId}, Success: {Success}, Failures: {Failures}, " +
            "WasQueued: {WasQueued}, Message: {Message}",
            plan.Id,
            result.SuccessCount,
            result.FailureCount,
            result.WasQueued,
            result.Message);
    }

    /// <summary>
    /// Log plan execution failure.
    /// </summary>
    public void LogExecutionFailed(PlanDTO plan, Exception ex)
    {
        _logger.LogError(ex, "Plan execution failed. PlanId: {PlanId}", plan.Id);
    }

    /// <summary>
    /// Log undo operation.
    /// </summary>
    public void LogUndoOperation(Guid planId, ExecutionResultDTO result)
    {
        _logger.LogInformation(
            "Undo operation completed. Original PlanId: {PlanId}, Success: {Success}, Message: {Message}",
            planId, result.SuccessCount, result.Message);
    }

    /// <summary>
    /// Log token deduction.
    /// </summary>
    public void LogTokenDeducted(int amount, int remaining, Guid planId)
    {
        _logger.LogDebug(
            "Token deducted. Amount: {Amount}, Remaining: {Remaining}, PlanId: {PlanId}",
            amount, remaining, planId);
    }

    /// <summary>
    /// Log queued plan processing.
    /// </summary>
    public void LogQueuedPlanProcessing(int queuedCount, DateTime processStartTime)
    {
        _logger.LogInformation(
            "Starting queued plan processing. QueuedCount: {QueuedCount}, ProcessStartTime: {StartTime}",
            queuedCount, processStartTime);
    }

    /// <summary>
    /// Log queued plans processing completion.
    /// </summary>
    public void LogQueuedPlanProcessingCompleted(ExecutionResultDTO result, int remainingQueued)
    {
        _logger.LogInformation(
            "Queued plan processing completed. Processed: {Processed}, Failures: {Failures}, " +
            "Remaining: {Remaining}, Message: {Message}",
            result.SuccessCount, result.FailureCount, remainingQueued, result.Message);
    }

    /// <summary>
    /// Log planner strategy change.
    /// </summary>
    public void LogPlannerStrategyChanged(string fromStrategy, string toStrategy)
    {
        _logger.LogInformation(
            "Planner strategy changed. From: {FromStrategy}, To: {ToStrategy}",
            fromStrategy, toStrategy);
    }

    /// <summary>
    /// Log plan offline queueing.
    /// </summary>
    public void LogPlanQueued(Guid planId, int totalQueued)
    {
        _logger.LogInformation(
            "Plan queued due to offline mode. PlanId: {PlanId}, TotalQueued: {TotalQueued}",
            planId, totalQueued);
    }

    /// <summary>
    /// Log token limit reached.
    /// </summary>
    public void LogTokenLimitReached(int used, int limit)
    {
        _logger.LogWarning(
            "Token limit reached. Used: {Used}, Limit: {Limit}",
            used, limit);
    }

    /// <summary>
    /// Log planner exception with context.
    /// </summary>
    public void LogPlannerException(string plannerType, Exception ex, string userInput)
    {
        _logger.LogError(ex, "Planner {PlannerType} threw exception. Input: '{Input}'", plannerType, userInput);
    }
}
